baseURL = "https://ykhatri.dev/"
languageCode = "en-us"
title = "Yougeshwar Khatri"
theme = ["hugo-PaperMod"]

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
title = "Yougeshwar Khatri"
description = "Cloud Architect | DevOps Engineer | Backend Developer"
keywords = [
  "aws",
  "cloud",
  "cloud-architect",
  "devops",
  "backend",
  "developer",
  "sre",
  "kubernetes",
  "terraform",
]
author = "Me"
defaultTheme = "dark"
showToc = true
TocOpen = false
draft = false
hidemeta = false
ShowReadingTime = true
ShowBreadCrumbs = true
# ShowPostNavLinks = true
ShowWordCount = true
UseHugoToc = true
disableScrollToTop = false

[outputs]
home = ["HTML", "RSS", "JSON"]

# Assets
[params.assets]
favicon = "images/favicon.ico"
favicon16x16 = "images/favicon-16x16.png"
favicon32x32 = "images/favicon-32x32.png"
apple_touch_icon = "images/apple-touch-icon.png"

# [params.label]
# icon = "images/apple-touch-icon.png"
# iconHeight = 100

# Profile image
[params.profileMode]
enabled = true
title = "Yougeshwar Khatri"
subtitle = "Cloud Architect | DevOps Engineer | Backend Developer | SRE"
imageUrl = "images/profile-picture.webp"
imageWidth = 300
imageHeight = 300

# Social Icons
[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/yougeshwar-khatri/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ypkkhatri"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/4098189/yougeshwar-khatri"

# Menu
[[menu.main]]
# identifier = "about"
name = "About"
url = "about/"
weight = 1

[[menu.main]]
# identifier = "Certs"
name = "Certs"
url = "certs/"
weight = 2

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 3

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 4

[[menu.main]]
name = "Search"
url = "search/"
weight = 5

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 6
